name: Build and Package

on:
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          rm -rf dist build
          pyinstaller --onefile \
            --name TrenchCoat \
            --hidden-import mpremote \
            --add-data "uf2:uf2" \
            trenchcoat.py

      - name: List dist folder
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrenchCoat-linux
          path: dist/TrenchCoat
          if-no-files-found: error

  build_windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if (Test-Path dist) { Remove-Item dist -Recurse -Force }
          if (Test-Path build) { Remove-Item build -Recurse -Force }
          pyinstaller --onefile --name TrenchCoat --hidden-import mpremote --add-data "uf2;uf2" trenchcoat.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrenchCoat-windows
          path: dist/TrenchCoat.exe
          if-no-files-found: error