name: Build and Package

on:
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          rm -rf dist build
          pyinstaller --onefile \
            --name TrenchCoat \
            --hidden-import mpremote \
            --hidden-import mpremote.main \
            --hidden-import ipaddress \
            trenchcoat.py

      - name: List dist folder
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-flasher-linux
          path: dist/TrenchCoat  # The single file on Linux

  build_windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller (Windows)
        shell: pwsh  # Using PowerShell
        run: |
          if (Test-Path dist) {Remove-Item dist -Recurse -Force}
          if (Test-Path build) {Remove-Item build -Recurse -Force}
          pyinstaller --onefile ^
            --name TrenchCoat ^
            --hidden-import mpremote ^
            --hidden-import mpremote.main ^
            --hidden-import ipaddress ^
            trenchcoat.py

      - name: List dist folder (Windows)
        shell: pwsh
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-flasher-windows
          path: dist/TrenchCoat.exe
