name: Build and Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pico-flasher-linux
            ext: ""
          - os: windows-latest
            artifact_name: pico-flasher-windows
            ext: ".exe"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PyInstaller build
        run: |
          rm -rf dist build
          pyinstaller \
            --onefile \
            --name TrenchCoat \
            --hidden-import mpremote \
            --hidden-import mpremote.main \
            --hidden-import ipaddress \
            trenchcoat.py

      - name: List dist on Linux
        if: matrix.os == 'ubuntu-latest'
        run: ls -la dist

      - name: List dist on Windows
        if: matrix.os == 'windows-latest'
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/TrenchCoat${{ matrix.ext }}
