name: Build and Deploy

on:
    push:
        branches:
            - '*'
    pull_request:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                        artifact_extension: ""
                    - os: macos-latest
                        artifact_extension: ""
                    - os: windows-latest
                        artifact_extension: ".exe"

        steps:
            - name: Checkout code
                uses: actions/checkout@v3

            - name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'

            - name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install pyinstaller

            - name: Build executable
                run: |
                    pyinstaller --onefile --add-data "PICO_CODE;PICO_CODE" --add-data "logo.png;." --icon=icon.ico --name "WarpedPinballProgrammer" main.py
                shell: bash

            - name: Upload executable artifact
                uses: actions/upload-artifact@v3
                with:
                    name: WarpedPinballProgrammer-${{ matrix.os }}
                    path: dist/WarpedPinballProgrammer${{ matrix.artifact_extension }}
