name: Build and Deploy

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      platform: linux
                      artifact_extension: ""
                    - os: macos-latest
                      platform: mac
                      artifact_extension: ""
                    - os: windows-latest
                      platform: win
                      artifact_extension: ".exe"

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller

            - name: Build executable
              run: |
                  pyinstaller --onefile --icon=icon.ico --name "WarpedPinballProgrammer-${{ matrix.platform }}" main.py
              shell: bash

            - name: Upload executable to GitHub Release
              uses: softprops/action-gh-release@v2
              if: ${{ github.event_name == 'release' }}
              with:
                  files: dist/WarpedPinballProgrammer-${{ matrix.platform }}${{ matrix.artifact_extension }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload executable as artifact
              uses: actions/upload-artifact@v4
              with:
                name: WarpedPinballProgrammer-${{ matrix.platform }}
                path: dist/WarpedPinballProgrammer-${{ matrix.platform }}${{ matrix.artifact_extension }}
